Health:
    prefix: /api/health
    resource: ../src/Health/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
    
User:
    prefix: /api/users
    resource: ../src/User/Infrastructure/Api/User/routes.yaml
    trailing_slash_on_root: false
    
Group:
    prefix: /api/groups
    resource: ../src/User/Infrastructure/Api/Group/routes.yaml
    trailing_slash_on_root: false
    
kernel:
    resource: ../src/Kernel.php
    type: annotation
